apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: lolc-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      component: helloworld
  template:
    metadata:
      labels:
        component: helloworld
    spec:
      containers:
        - name: helloworld
          image: savindyadhananjani/lolc-hello-world:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: lolc-devops
spec:
  type: NodePort
  selector:
    component: helloworld
  ports:
    - port: 8080
      targetPort: 8081